repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.1.4
    hooks:
      - id: biome-check
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.2
    hooks:
      - id: check-jsonschema
        files: biome.json
        args: ["--check-metaschema"]